version: 1.0.{build}
image: Visual Studio 2019
configuration: release
before_build:
- ps: ./generate.bat
build:
  project: build/zonetool.sln
  verbosity: minimal
test: off
artifacts:
- path: build/bin/*.dll
- path: build/bin/*.pdb
deploy:
- provider: GitHub
  auth_token:
    secure: IyUTCaq8tOpcOwDfqa2bH2UCEgPNoLpgqZtJOetSchzZcs1rJT8b/oQ/DTq2ecwc
  on:
    branch: master